;;; Automatically generated by ‘recentf’ on Thu Feb 23 16:43:03 2017.

(setq recentf-list
      '(
        "/Users/andrewwilliams/code/elixir/weather/lib/weather.ex"
        "/Users/andrewwilliams/.emacs.d/init.el"
        "/Users/andrewwilliams/.emacs.d/elpa/no-littering-0.5.4/no-littering-autoloads.el"
        "/Users/andrewwilliams/.emacs.d/settings/skunkworks.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
